version: "3.9"
services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=MY_DB
    ports:
      - "5432:5432"
    volumes:
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d MY_DB" ]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: "rabbitmq:3.12.6-management-alpine"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "admin"
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 5s
      timeout: 20s
      retries: 5
  bot:
    build:
      context: .
      dockerfile: ./cmd/bot/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
  server:
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: ./cmd/server/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
networks:
  default:
    driver: bridge